allowBuilds:
  '@parcel/watcher': true
  core-js: true
  electron: set this to true or false
  electron-winstaller: true
  esbuild: true
  ffmpeg-static: true
  lzma-native: set this to true or false
  sharp: true
  usocket: true
nodeLinker: hoisted
